#define WAITING 1
#define WAITING 1
#define WAITING 1
#define MSG_START 2
#define COMMAND 3
#define FORWARD 4
#define BACKWARD 5
#define LEFT 6
#define RIGHT 7
#define MSG_END 8
#define ACK 9
#define ACTION_COMPLETE 10
#define PARAMETER1 11
#define PARAMETER2 12
#define REPORTING 13
#define GET_X 14
#define GET_Y 15
#define GET_BATT 16
#define DATA_IN 17
#define LISTENING_FOR_THE_END 19
#define WTF 20
#define LISTENING_FOR_A_CHECKSUM 21
#define LISTENING 22
#define INVALID_COMMAND 23
#define BAD_CHECKSUM 24
#define BAD_MESSAGE_STRUCTURE 25
#define MOVING 26
#define GET_STATUS 27
#define PEN_UP 28
#define PEN_DOWN 29
